name: Test Flow

on:
  push:
    branches: ["main"]

env:
  APP_NAME: MyApp
  Environment: Dev
  Owner: Harsh
  message: ${{secrets.TEST_VAR}}  

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
        - name: Display hello
          run: echo $APP_NAME
        - name: Environment
          run: echo $Environment
        - name: Owner Name
          run: echo $Owner
        - name: Display Secrets
          run: echo $message
